amplicons:
  dpy-10:
    fasta: /home/edanner/workspace/pigx_crispr/sample_data/amplicons/amplicon_dpy-10.fa
    cutsites: /home/edanner/workspace/pigx_crispr/sample_data/cutsites/sgRNA_cutsites_dpy-10.txt
  lin-41: 
    fasta: /home/edanner/workspace/pigx_crispr/sample_data/amplicons/amplicon_lin-41.fa
    cutsites: /home/edanner/workspace/pigx_crispr/sample_data/cutsites/sgRNA_cutsites_lin-41.txt

sample_sheet: /home/edanner/workspace/pigx_crispr/sample_data/sample_sheet.csv

reads-dir: /home/edanner/workspace/pigx_crispr/sample_data/reads
output-dir: /home/edanner/workspace/pigx_crispr/sample_data/output
source-dir: /home/edanner/workspace/pigx_crispr/

adapters: /home/edanner/workspace/pigx_crispr/sample_data/adapters/TruSeq2-SE.fa

nodeN: 4

tools:
    Rscript: /home/edanner/anaconda3/bin/Rscript

comparisonsFile: /home/edanner/workspace/pigx_crispr/sample_data/comparisons.tsv
